#GET
GET http://localhost:8087/api/v1/disciplina
Content-Type: application/json
###


#GET
GET http://localhost:8087/api/v1/disciplina/2
Content-Type: application/json
###

#POST
POST http://localhost:8087/api/v1/disciplina
Content-Type: application/json

{
    "descricao": "Matemática"
}
###

#POST
POST http://localhost:8087/api/v1/disciplina
Content-Type: application/json

{
    "descricao": "Português"
}
###